### ISSUE TITLE
Pixel preview cutout is applied all the time, not just when in preview

### ISSUE THREAD

**Issue by Adolar0042** [osuplace/templateManager#43]
[This line](https://github.com/osuplace/templateManager/blob/main/src/reddit.ts#L10) seems to be improperly applied to the cursor when not in preview mode (as seen in the following image)
![image](https://github.com/osuplace/templateManager/assets/39769465/21073fc6-99e6-4197-920c-5ff9c5272879)

**Comment by LittleEndu** [comment]
We know, but we don't care enough to fix it
